### PR TITLE
Implemented ExpressionStarter<T> to eliminate the default 1=0 or 1=1 stub expressions

### PR DESCRIPTION
**Pull request by rhyous**
See comments from here: 
https://github.com/scottksmith95/LINQKit/issues/30

### CODE REVIEW

**Comment by StefH** [comment]
Quick question ; is the 'Extend' method also gone?

**Comment by rhyous** [comment]
I don't see it. Perhaps I removed too much?
I can easily put the extend method back before you accept the pull request if you want.

**Comment by StefH** [comment]
Yes please put that one back.

**Comment by rhyous** [comment]
I put it back. I didn't see any unit tests specific to that method. But all Unit Tests are still passing after restoring that method.

**Comment by rhyous** [comment]
I updated the readme and added the Extend extension method to ExpressionStarter<T> too.

**Comment by StefH** [comment]
Thanks.

I'll merge all changes into the 'development' branch.

**Comment by StefH** [comment]
Merged into development branch, please review. If it's all correct, I'll merge to master and create a new NuGet.

**Comment by rhyous** [comment]
I checked out the development branch. I think there is an issue with the DbAsyncTests breaking the build.

The type or namespace name 'TestContext' could not be found (are you missing a using directive or an assembly reference?)	LinqKit.Microsoft.EntityFrameworkCore.Tests..NETCoreApp,Version=v1.0

It looks like a using statement is comment out and it shouldn't be?

Line 7 //using LinqKit.EntityFramework.Tests;

Once I uncommented that, I had to change a few variables called `db` to `_db`. Then it all builds. 

I ran the Unit Tests and it all passes. So update DbAsyncTests and it will be good to go. I had to modify four lines.

```
line 7  using LinqKit.EntityFramework.Tests;
line 29            _db = new TestContext(builder.Options);
line 30            _db.Database.EnsureCreated();
line 49            _db.Database.EnsureDeleted();

```

**Comment by StefH** [comment]
Fix in dev.

**Pull request merged**
