### PR TITLE
EntityFramework 6.3.0 and Microsoft.EntityFrameworkCore 3.0.0

### PR DESCRIPTION
**Pull request by StefH**

### CODE REVIEW

**Comment by finalcut** [comment]
This seems like a really valuable merge request.  I wonder if there is just something simple in the appveyor build that can happen to make sure the newer sdk is installed so this will build properly?

**Comment by StefH** [comment]
@finalcut Actually I think moving to AzurePipelines is even better.
I'll take a look if I can start a PR on this after next week.

**Comment by finalcut** [comment]
awesome. I agree azure pipelines would probably be better in the long run.  Thanks for being so responsive!

**Comment by onionhammer** [comment]
You guys could just add in github actions now; it's built in

**Pull request merged**
