### PR TITLE
Handle expressions in properties.

### LINKED ISSUE #124: LINQKit does not support referencing expressions stored in properties (InvalidCastException)
Running the following program:

```CSharp
using System;
using System.Linq.Expressions;
using LinqKit;

namespace Test
{
    class Program
    {
        public static Expression<Func<int, int>> Foo => x => x * 6;

        static void Main(string[] args)
        {
            Expression<Func<int, int>> bar = x => Foo.Invoke(x * 7);
            Expression<Func<int, int>> barExpanded = bar.Expand(); // <-- System.InvalidCastException
            Console.WriteLine(barExpanded.Invoke(1));
        }
    }
}
```

Fails with

```
System.InvalidCastException: Unable to cast object of type 'System.Linq.Expressions.PropertyExpression' to type 'System.Linq.Expressions.LambdaExpression'.
   at LinqKit.ExpressionExpander.VisitMethodCall(MethodCallExpression m) in C:\projects\LINQKit\src\LinqKit.Core\ExpressionExpander.cs:line 78
   at LinqKit.ExpressionVisitor.Visit(Expression exp) in C:\projects\LINQKit\src\LinqKit.Core\ExpressionVisitor.cs:line 71
   at LinqKit.ExpressionVisitor.VisitLambda(LambdaExpression lambda) in C:\projects\LINQKit\src\LinqKit.Core\ExpressionVisitor.cs:line 353
   at LinqKit.ExpressionVisitor.Visit(Expression exp) in C:\projects\LINQKit\src\LinqKit.Core\ExpressionVisitor.cs:line 73
   at LinqKit.Extensions.Expand[TDelegate](Expression`1 expr) in C:\projects\LINQKit\src\LinqKit.Core\Extensions.cs:line 54
   at Test.Program.Main(String[] args) in C:\projects\LINQKit\Test\Program.cs:line 14
```

This may be related to #89 where it's a delegate rather than an expression in a property that causes problems.

### PR DESCRIPTION
**Pull request by poizan42**
Fixes #124

### CODE REVIEW

**Comment by poizan42** [comment]
This also ended up handling expressions in fields where the object is a captured variable.

**Comment by sdanyliv** [comment]
@StefH, i think I have already fixed this issue. Probably tests can be grabbed from this PR.

**Comment by poizan42** [comment]
Uhm yeah I think the issues were fixed in #127 with a slightly different approach. I can take a look at making a PR with just the tests that are still missing.

**Comment by StefH** [comment]
@poizan42 
Can you fix merge conflicts?

**Comment by sdanyliv** [comment]
@StefH, don’t merge this PR, only tests are needed.

**Comment by StefH** [comment]
You mean I need to wait on tests?

Or is this PR only about tests?

**Comment by sdanyliv** [comment]
I mean that issue addressed by this PR already fixed, so we can reuse just tests.

**Comment by StefH** [comment]
@sdanyliv 
Thanks for the information.

Unit tests are added to master.

**Pull request closed without merging**
