### PR TITLE
LeftJoin

### PR DESCRIPTION
**Pull request by TanielianVB**
Felt the need to create a generic LeftJoin method and had to use LinqKit. So since used it and made 2 corrections to the code, I thought I should share.

### CODE REVIEW

**Comment by flier268** [comment]
Excuse me, I can not found the code in master now
Anything happen?

**Comment by TanielianVB** [comment]
True. I can't find it either.

**Comment by StefH** [comment]
@flier268 @TanielianVB 
I think I did remove this by accident.
(see https://github.com/scottksmith95/LINQKit/pull/33)

I'll see if I can bring this back.

**Comment by StefH** [comment]
@TanielianVB 
I've added the extension method.
https://github.com/scottksmith95/LINQKit/pull/144

However, do you maybe have a test-scenario or unit test for this?

**Comment by TanielianVB** [comment]
Unfortunately, I don't anymore. 😢

**Pull request merged**
