### PR TITLE
Refactor projects

### PR DESCRIPTION
**Pull request by StefH**

### CODE REVIEW

**Comment by StefH** [comment]
Please do a code-review.

**Comment by Thorium** [comment]
So now LinqKit.Core is basic (net standard) version with no references?
And LinqKit is a .NET45 version with EF6 and LinqKit.Core reference?

Looks good to me!

**Comment by StefH** [comment]
- LinqKit.Core supports a lot of frameworks and has no reference to EntityFramework
- LinqKit supports .NET 45x and .NET 4.6x but has no _reference_ to LinqKit.Core, it uses the same C$ source files. Referencing is not possible.

**Comment by Thorium** [comment]
Ok. Sounds ok for me still.

**Comment by StefH** [comment]
OK, I'll merge this PR?

**Comment by StefH** [comment]
@Thorium : should I merge this PR and create new NuGets?

**Comment by Thorium** [comment]
I think you can.

**Pull request merged**
