### PR TITLE
#14 Include(...) after AsExpandable()

### PR DESCRIPTION
**Pull request by doboczyakos**
Fixed

### CODE REVIEW

**Comment by StefH** [comment]
Hello @doboczyakos,

Thanks for this PR.

Is it possible that you create a console app which identifies this problem? And make a new PR for this on master.

Then we are sure that this PR does fix the issue.

And is there also some documentation which needs to be updated?

**Comment by doboczyakos** [comment]
We identified the problem in our enterprise application and tested this fix with a forked package.
Are you sure you want a console application or would it be better to add a new testcase for this?
The only thing you have to document is that .AsExpandable().Include() is working with EF Core from now on... but it uses internal API, there's no other option to fix it, so it can cause build error with future versions of EF Core if they modify this API. Anyway it's the same in all EF Core versions until 6 so I don't expect breaking change.

**Comment by StefH** [comment]
> Are you sure you want a console application or would it be better to add a new testcase for this?
If a unit-test would be possible, that is preferred.

**Comment by doboczyakos** [comment]
Microsoft.EntityFrameworkCore.Query.Internal is being used since 2016 in LinqKit so I don't think it's something we should be afraid of.
I'm committing a testcase to this PR today

**Comment by doboczyakos** [comment]
Sorry, I create a new branch for the test to be able to test is with both versions

**Comment by sdanyliv** [comment]
@doboczyakos, `WithExpressionExpanding` is not suitable for you?

**Comment by davidnemeti** [comment]
@sdanyliv, although `optionsBuilder.WithExpressionExpanding()` works properly with `.Include()`; however we have several places where we use explicit `.AsExpandable()` in common code. In these common code we cannot apply `optionsBuilder.WithExpressionExpanding()`, because we do not have access to the concrete `DbContext` class there. Still, the common code use `.Invoke()` heavily, so `.AsExpandable()` is necessary; and we should not assume that the code that uses it is going to use `optionsBuilder.WithExpressionExpanding()`.

Moreover, the situation now is very fragile, because as soon as a developer writes `.AsExpandable().Include()` explicitly in the code, then the `.Include()` behavior will not work, regardless the use of `optionsBuilder.WithExpressionExpanding()`.

**Comment by sdanyliv** [comment]
You are right. I don‘t know why Include code i so restrictive to IQueryable implementation.

**Comment by doboczyakos** [comment]
@StefH https://github.com/scottksmith95/LINQKit/pull/165

**Comment by davidnemeti** [comment]
@StefH , how is the merge of the pull request going? Can we help anything?

**Comment by StefH** [comment]
@davidnemeti 
I'll first merge the unit-test PR and then this one.

**Comment by doboczyakos** [comment]
What's going on with .netcoreapp 2.1?
"Testhost process exited with error: It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.1.0' (x64) was not found."

**Comment by doboczyakos** [comment]
https://github.com/dotnet/core/issues/6640

**Comment by StefH** [comment]
@doboczyakos 
I see.

I'll remove this test and replace it by other frameworks.

**Pull request merged**
